planets = {
    'sun': {
                'image_path':'objects/sun/sun.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':30.0,
                'rotation_ratio_relative_to_earth': 0.0,
                'revolution_ratio_relative_to_earth': 0.0,
                'distance_from_sun':0.0,
                'initial_position': 0,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'mercury': {
                'image_path':'objects/mercury/mercury.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':0.38,
                'rotation_ratio_relative_to_earth': 1.0,
                'revolution_ratio_relative_to_earth': 0.1,
                'distance_from_sun':35.98,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'venus': {
                'image_path':'objects/venus/venus.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':0.95,
                'rotation_ratio_relative_to_earth': 1,
                'revolution_ratio_relative_to_earth': 0.1,
                'distance_from_sun':67.24,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'earth': {
                'image_path':'objects/earth/earth.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':1.0,
                'rotation_ratio_relative_to_earth': 1,
                'revolution_ratio_relative_to_earth': 0.01,
                'distance_from_sun':92.96,
                'initial_position': 0,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'mars': {
                'image_path':'objects/mars/mars.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':0.53,
                'rotation_ratio_relative_to_earth': 0.2,
                'revolution_ratio_relative_to_earth': 0.1,
                'distance_from_sun':141.6,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'jupiter': {
                'image_path':'objects/jupiter/jupiter.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':11.2,
                'rotation_ratio_relative_to_earth': 0.002,
                'revolution_ratio_relative_to_earth': 0.1,
                'distance_from_sun':483.8,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'saturn': {
                'image_path':'objects/saturn/saturn.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':9.45,
                'rotation_ratio_relative_to_earth': 0.2,
                'revolution_ratio_relative_to_earth': 0.1,
                'distance_from_sun':890.8,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'uranus': {
                'image_path':'objects/uranus/uranus.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':4.0,
                'rotation_ratio_relative_to_earth': 0.2,
                'revolution_ratio_relative_to_earth': 0.1,
                'distance_from_sun':1784.0,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'neptune': {
                'image_path':'objects/neptune/neptune.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':3.88,
                'rotation_ratio_relative_to_earth': 0.002,
                'revolution_ratio_relative_to_earth': 0.1,
                'distance_from_sun':2193,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    'stars': {
                'image_path':'objects/StarsMap.jpg',
                'texture':'',
                'size_ratio_relative_to_earth':2000,
                'rotation_ratio_relative_to_earth': 0.0,
                'revolution_ratio_relative_to_earth': 0.0,
                'distance_from_sun':0,
                'Global_ambient': [0.8, 0.8, 0.9, 0.1],
                'Light_ambient': [ 0.3, 0.3, 0.3, 1.0],
                'Light_diffuse': [ 0.25, 0.25, 0.25, 1.0],
                'Light_specular': [ 0.9, 0.9, 0.9, 1.0],
                'Light_location': [ 0, 0, 0],
                'Material_ambient': [ 0.4, 0.4, 0.4, 1.0],
                'Material_diffuse': [ 0.15, 0.15, 0.15, 1.0],
                'Material_specular': [ 1.0, 1.0, 1.0, 1.0],
                'Material_shininess': [0.95],
                },
    # 'cruiser': {
    #             'image_path':'objects/cruiser.bmp',
    #             'texture':'',
    #             'size_ratio_relative_to_earth':10,
    #             'rotation_ratio_relative_to_earth': 0.0,
    #             'revolution_ratio_relative_to_earth': 0.0,
    #             'distance_from_sun':0,
    #             }
            }